language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"
before_install:
  - pip install --upgrade pip
install:
  - pip install --no-cache-dir --editable .
script:
  - metacov --help
  - pytest
  
